version: '3.8'
services:
  postgres:
    image: postgres
    container_name: shopme-postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=shopmeDb
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: